/** =================================================================*
 * @file   control_config.h
 * @brief  CPU0の音源追従・障害物回避の調整値
 * ================================================================= */
#ifndef SEROV_CPU0_CONFIG_CONTROL_H
#define SEROV_CPU0_CONFIG_CONTROL_H

#define CPU0_AUTONOMY_MODE_SOUND_FOLLOW    (0U)
#define CPU0_AUTONOMY_MODE_SENSOR_RULE     (1U)
#define CPU0_AUTONOMY_MODE                 (CPU0_AUTONOMY_MODE_SENSOR_RULE)

#define CPU0_SENSOR_CLEAR_DISTANCE_MM      (1000U)
#define CPU0_SENSOR_CAUTION_DISTANCE_MM    (650U)
#define CPU0_SENSOR_SIDE_DISTANCE_MM       (450U)
#define CPU0_SENSOR_HARD_STOP_DISTANCE_MM  (250U)
#define CPU0_SENSOR_BLOCKED_DISTANCE_MM    (350U)
#define CPU0_SENSOR_FORWARD_RPM            (100)
#define CPU0_SENSOR_CAUTION_RPM            (80)
#define CPU0_SENSOR_TURN_OUTER_RPM         (90)
#define CPU0_SENSOR_TURN_INNER_RPM         (70)
#define CPU0_SENSOR_TURN_STEERING_DEG      (35)
#define CPU0_SENSOR_IMU_MAX_TILT_MG        (700)
#define CPU0_SENSOR_IMU_MAX_SHOCK_L1_MG    (2400)
#define CPU0_SENSOR_IMU_MAX_GYRO_DPS_X10   (2000)

#define CPU0_SOUND_DOA_ZERO_OFFSET_DEG     (0)
#define CPU0_SOUND_DOA_CLOCKWISE_POSITIVE  (0U)
#define CPU0_SOUND_TRIGGER_DBFS_X100       (-4500)
#define CPU0_SOUND_RELEASE_DBFS_X100       (-4800)
#define CPU0_SOUND_DOA_SETTLE_MS           (500U)
#define CPU0_SOUND_DOA_ACQUIRE_TIMEOUT_MS  (2000U)
#define CPU0_SOUND_DOA_SAMPLE_COUNT        (5U)
#define CPU0_SOUND_DOA_STABLE_WIDTH_DEG    (20)
#define CPU0_SOUND_FRONT_TOLERANCE_DEG     (15)
#define CPU0_SOUND_STEERING_MIN_DEG        (20)
#define CPU0_SOUND_STEERING_MAX_DEG        (45)
#define CPU0_SOUND_LINK_STABLE_MS          (500U)
#define CPU0_SOUND_OBSERVATION_TIMEOUT_MS  (600U)
#define CPU0_SOUND_STEER_SETTLE_MS         (500U)
#define CPU0_SOUND_MOVE_STEP_MS            (1000U)
#define CPU0_SOUND_LISTEN_SETTLE_MS        (500U)
#define CPU0_SOUND_COOLDOWN_RELEASE_MS     (200U)
#define CPU0_SOUND_MOVE_LEFT_RPM           (120)
#define CPU0_SOUND_MOVE_RIGHT_RPM          (120)
#define CPU0_SOUND_TURN_INNER_RPM          (90)
#define CPU0_STEERING_SERVO_OUTPUT_SIGN    (-1)

#endif /* SEROV_CPU0_CONFIG_CONTROL_H */
